### ISSUE TITLE
Not a bug , But a query 

### ISSUE THREAD

**Issue by vikrantyadav7** [zezo357/video_player_dart_vlc#1]
hey
I have used dart_vlc to make a video streaming app. That only runs on android and ios only 
. I want to provide desktop support too.
So i saw your library in the documentation it said i just have to call a single function 
`initVideoPlayerDartVlcIfNeeded();`
I wanted to know if by doing this will my currrent app work on windows and linux too ?

**Comment by abdelaziz-mahdy** [comment]
Yes it should.

This is just a video_player platform interface to make video player package work on windows and Linux using dart_vlc
