### ISSUE TITLE
Need Documentation

### ISSUE THREAD

**Issue by Sachintermux** [zezo357/video_player_dart_vlc#2]
i want to use this plugin in my flutter desktop project for playing online video. but i don't find any documentation please help me to implement this.

**Comment by abdelaziz-mahdy** [comment]
initVideoPlayerDartVlcIfNeeded();


Add this to the main of your app

void main(){
initVideoPlayerDartVlcIfNeeded();

//Run app should be here 
}

**Comment by abdelaziz-mahdy** [comment]
This will make the flutter video player package work on windows and Linux also

**Comment by abdelaziz-mahdy** [comment]
You can use this package which is much more documented
 https://pub.dev/packages/flutter_meedu_videoplayer

And uses this package
